version: '3'
services:
  esaude-platform-tomcat:
    build: tomcat
    ports:
      - "8080:8080"
    container_name: esaude-platform-tomcat
    depends_on:
      - esaude-platform-mysql
    networks:
      - network
    volumes:
      - data:/opt/esaude/data
    hostname: esaude-platform-tomcat
    restart: unless-stopped
  esaude-platform-mysql:
    build: mysql
    container_name: esaude-platform-mysql
    networks:
      - network
    volumes:
      - data:/opt/esaude/data
    hostname: esaude-platform-mysql
    restart: unless-stopped
networks:
  network:
volumes:
  data:
