version: '2'
services:
  esaude-platform-tomcat:
    build: tomcat
    ports:
      - "8080:8080"
    container_name: esaude-platform-tomcat
    depends_on:
      - esaude-platform-mysql
    networks:
      - network
  esaude-platform-mysql:
    build: mysql
    container_name: esaude-platform-mysql
    networks:
      - network
    volumes:
      - data:/opt/esaude/data
networks:
  network:
volumes:
  data:
