version: '2'
services:
  esaude-platform-tomcat:
    image: esaude-docker-platform-docker.bintray.io/tomcat:1.2.7
    ports:
      - "8080:8080"
    container_name: esaude-platform-tomcat
    depends_on:
      - esaude-platform-mysql
  esaude-platform-mysql:
    image: esaude-docker-platform-docker.bintray.io/mysql:1.2.7
    container_name: esaude-platform-mysql
